import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";

import { Navbar } from "../components/Navbar";
// import { Web3Modal } from "../context/web3modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          {/* <Web3Modal> */}
          <Navbar />
          <div>{children}</div>
          {/* <Footer /> */}
          {/* <PopupWidget /> */}
          {/* </Web3Modal> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
